### ISSUE TITLE
[Wii] [GX] Some slowdown on 3D bonus stages

### ISSUE THREAD

**Issue by saulfabregwiivc** [Mefiresu/RSDKv5-Decompilation#10]
Most of the time when in 2D levels the game runs pretty fine (Sonic Mania in this case), but when on these 3D bonus stages, the game runs slow.
Any way for see and optimize the code for get the 3D stages running at full speed on Wii?
Thanks for porting this to Wii :D

**Comment by Mefiresu** [comment]
I'm aware of this, unfortunately this requires re-implementing most of the Scene3D code to render everything using the GPU, which would take time.

**Comment by SonicSman2000** [comment]
I wonder how you plan on making it use the gpu instead of the cpu have you made an attempt yet? So far it looks good despite some game breaking moments hope this project isn't dead

**Comment by Mefiresu** [comment]
I haven't attempted a complete GPU implementation yet, however I currently have some WIP improvements that makes special stages run quite a bit faster.

**Comment by SonicSman2000** [comment]
what did you do exactly? and any predictions for a new release?

**Comment by Mefiresu** [comment]
I'm mainly making optimizations on the 3D rendering algorithms used in RSDKv5.
No ETA for a new release yet, it'll get released once it's ready (currently, the optimizations pretty much breaks a lot of things, so they might not make it into the next release).

**Comment by deepfriedfilth** [comment]
🎉 Fixed in release [v0.5.0](https://github.com/Mefiresu/RSDKv5-Decompilation/releases/tag/v0.5.0) (to apply additional mod mentioned there, see [instructions](https://gbatemp.net/threads/sonic-mania-for-wii.619890/page-11#post-10137466) on GBAtemp thread)

**Comment by Mefiresu** [comment]
> 🎉 Fixed in release [v0.5.0](https://github.com/Mefiresu/RSDKv5-Decompilation/releases/tag/v0.5.0) (to apply additional mod mentioned there, see [instructions](https://gbatemp.net/threads/sonic-mania-for-wii.619890/page-11#post-10137466) on GBAtemp thread)

Not completely fixed, but performance sure improved a lot.
I'm still hoping to get it running at full speed without any performance mods.

**Comment by MegaBlue92** [comment]
This runs very well now. If anyone is interested I made a less decorations mod that seems to keep a constant 60fps opposed to the no decorations mod as that mod seems very empty.
